export const allCountries = [
  "Afghanistan",
  "Albanien",
  "Algerien",
  "Andorra",
  "Angola",
  "Antigua und Barbuda",
  "Argentinien",
  "Armenien",
  "Aserbaidschan",
  "Australien",
  "Ägypten",
  "Bahamas",
  "Bahrain",
  "Bangladesch",
  "Barbados",
  "Belarus (Weißrussland)",
  "Belgien",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivien",
  "Bosnien und Herzegowina",
  "Botswana",
  "Brasilien",
  "Brunei",
  "Bulgarien",
  "Burkina Faso",
  "Burundi",
  "Chile",
  "China",
  "Costa Rica",
  "Demokratische Republik Kongo",
  "Deutschland",
  "Dominica",
  "Dominikanische Republik",
  "Dschibuti",
  "Dänemark",
  "Ecuador",
  "El Salvador",
  "Elfenbeinküste",
  "Eritrea",
  "Estland",
  "Eswatini",
  "Fidschi",
  "Finnland",
  "Frankreich",
  "Gabun",
  "Gambia",
  "Georgien",
  "Ghana",
  "Grenada",
  "Griechenland",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Indien",
  "Indonesien",
  "Irak",
  "Iran",
  "Irland",
  "Island",
  "Israel",
  "Italien",
  "Jamaika",
  "Japan",
  "Jemen",
  "Jordanien",
  "Kambodscha",
  "Kamerun",
  "Kanada",
  "Kap Verde",
  "Kasachstan",
  "Katar",
  "Kenia",
  "Kirgisistan",
  "Kiribati",
  "Kolumbien",
  "Komoren",
  "Kongo (Republik)",
  "Kroatien",
  "Kuba",
  "Kuwait",
  "Laos",
  "Lesotho",
  "Lettland",
  "Libanon",
  "Liberia",
  "Libyen",
  "Liechtenstein",
  "Litauen",
  "Luxemburg",
  "Madagaskar",
  "Malawi",
  "Malaysia",
  "Malediven",
  "Mali",
  "Malta",
  "Marokko",
  "Marshallinseln",
  "Mauretanien",
  "Mauritius",
  "Mexiko",
  "Mikronesien",
  "Moldawien",
  "Monaco",
  "Mongolei",
  "Montenegro",
  "Mosambik",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Niederlande",
  "Neuseeland",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Nordkorea",
  "Nordmazedonien",
  "Norwegen",
  "Oman",
  "Österreich",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua-Neuguinea",
  "Paraguay",
  "Peru",
  "Philippinen",
  "Polen",
  "Portugal",
  "Ruanda",
  "Rumänien",
  "Russland",
  "Salomonen",
  "Sambia",
  "Samoa",
  "San Marino",
  "Saudi-Arabien",
  "Schweden",
  "Schweiz",
  "Senegal",
  "Serbien",
  "Seychellen",
  "Sierra Leone",
  "Simbawe",
  "Singapur",
  "Slowakei",
  "Slowenien",
  "Somalia",
  "Spanien",
  "Sri Lanka",
  "St. Kitts und Nevis",
  "St. Lucia",
  "St. Vincent und die Grenadinen",
  "Sudan",
  "Suriname",
  "Syrien",
  "São Tomé und Príncipe",
  "Südafrika",
  "Südkorea",
  "Südsudan",
  "Tadschikistan",
  "Taiwan",
  "Tansania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad und Tobago",
  "Tschad",
  "Tschechien",
  "Tunesien",
  "Turkmenistan",
  "Tuvalu",
  "Türkei",
  "Uganda",
  "Ukraine",
  "Ungarn",
  "Uruguay",
  "Usbekistan",
  "Vanuatu",
  "Vatikanstadt",
  "Venezuela",
  "Vereinigte Arabische Emirate",
  "Vereinigte Staaten",
  "Vereinigtes Königreich",
  "Vietnam",
  "Zentralafrikanische Republik",
  "Zypern"
];

export interface UserAcc {
  id: string;
  firstname: string;
  name: string;
  email: string;
  type: string;
  street: string;
  hNumber: string;
  pCode: string;
  town: string;
  country: string;
}

export const productMaterials = ["Holz", "Metall", "Kunststoff", "Stoff", "Halbmetall"];
export const productColors = ["Rot", "Blau", "Grün", "Schwarz", "Weiß", "Beige", "Hellblau", "Braun", "Dunkelbraun", "Hellbraun", "Rosa", "Lila", "Hellgrün"];
export const prodouctCategories = ["Dekoration", "Möbel", "Spielzeug", "Küche", "Auto Zubehör", "Fashion", "Elektronik", "Haustier Zubehör", "Beauty und Gesundheit"];

export const productCategoryColors: Record<string, string> = {
  "Dekoration": "#FFB6C1",
  "Möbel": "#8B4513",
  "Spielzeug": "#FFD700",
  "Küche": "#FF6347",
  "Auto Zubehör": "#4682B4",
  "Fashion": "#DA70D6",
  "Elektronik": "#20B2AA",
  "Haustier Zubehör": "#90EE90",
  "Beauty und Gesundheit": "#FF69B4",
};

export class ProductDBDTO {
  id!: string;                  // UUID
  name!: string;                // Produktname
  description!: string;
  crowd!: number;
  minCrowd!: number;
  price!: number;
  deliverable!: number;         // Lieferzeit in Tagen
  deliverableAbroad!: number;   // Lieferzeit ins Ausland
  material!: string;
  color!: string;
  category!: string;
  isAvailible!: boolean;
  createFrom!: string;          // User-ID (Fremdschlüssel)
  pictures?: PictureCallDto[]; // optional

  constructor(partial: Partial<ProductDBDTO>) {
    Object.assign(this, partial);
  }
}

interface PictureCallDto {
  fileName: string;
}