export const allCountries = [
  "Afghanistan",
  "Albanien",
  "Algerien",
  "Andorra",
  "Angola",
  "Antigua und Barbuda",
  "Argentinien",
  "Armenien",
  "Australien",
  "Österreich",
  "Aserbaidschan",
  "Bahamas",
  "Bahrain",
  "Bangladesch",
  "Barbados",
  "Belarus (Weißrussland)",
  "Belgien",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivien",
  "Bosnien und Herzegowina",
  "Botswana",
  "Brasilien",
  "Brunei",
  "Bulgarien",
  "Burkina Faso",
  "Burundi",
  "Kambodscha",
  "Kamerun",
  "Kanada",
  "Kap Verde",
  "Zentralafrikanische Republik",
  "Tschad",
  "Chile",
  "China",
  "Kolumbien",
  "Komoren",
  "Kongo (Republik)",
  "Demokratische Republik Kongo",
  "Costa Rica",
  "Kroatien",
  "Kuba",
  "Zypern",
  "Tschechien",
  "Dänemark",
  "Dschibuti",
  "Dominica",
  "Dominikanische Republik",
  "Ecuador",
  "Ägypten",
  "El Salvador",
  "Äquatorialguinea",
  "Eritrea",
  "Estland",
  "Eswatini",
  "Äthiopien",
  "Fidschi",
  "Finnland",
  "Frankreich",
  "Gabun",
  "Gambia",
  "Georgien",
  "Deutschland",
  "Ghana",
  "Griechenland",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Ungarn",
  "Island",
  "Indien",
  "Indonesien",
  "Iran",
  "Irak",
  "Irland",
  "Israel",
  "Italien",
  "Elfenbeinküste",
  "Jamaika",
  "Japan",
  "Jordanien",
  "Kasachstan",
  "Kenia",
  "Kiribati",
  "Nordkorea",
  "Südkorea",
  "Kuwait",
  "Kirgisistan",
  "Laos",
  "Lettland",
  "Libanon",
  "Lesotho",
  "Liberia",
  "Libyen",
  "Liechtenstein",
  "Litauen",
  "Luxemburg",
  "Madagaskar",
  "Malawi",
  "Malaysia",
  "Malediven",
  "Mali",
  "Malta",
  "Marokko",
  "Marshallinseln",
  "Mauretanien",
  "Mauritius",
  "Mexiko",
  "Mikronesien",
  "Moldawien",
  "Monaco",
  "Mongolei",
  "Montenegro",
  "Mosambik",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Niederlande",
  "Neuseeland",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Nordmazedonien",
  "Norwegen",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua-Neuguinea",
  "Paraguay",
  "Peru",
  "Philippinen",
  "Polen",
  "Portugal",
  "Katar",
  "Rumänien",
  "Russland",
  "Ruanda",
  "St. Kitts und Nevis",
  "St. Lucia",
  "St. Vincent und die Grenadinen",
  "Samoa",
  "San Marino",
  "São Tomé und Príncipe",
  "Saudi-Arabien",
  "Senegal",
  "Serbien",
  "Seychellen",
  "Sierra Leone",
  "Singapur",
  "Slowakei",
  "Slowenien",
  "Salomonen",
  "Somalia",
  "Südafrika",
  "Südsudan",
  "Spanien",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Schweden",
  "Schweiz",
  "Syrien",
  "Taiwan",
  "Tadschikistan",
  "Tansania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad und Tobago",
  "Tunesien",
  "Türkei",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "Vereinigte Arabische Emirate",
  "Vereinigtes Königreich",
  "Vereinigte Staaten",
  "Uruguay",
  "Usbekistan",
  "Vanuatu",
  "Vatikanstadt",
  "Venezuela",
  "Vietnam",
  "Jemen",
  "Sambia",
  "Simbawe"
];

export interface UserAcc {
  id: string;
  firstname: string;
  name: string;
  email: string;
  isAdmin: boolean;
  street: string;
  hNumber: string;
  pCode: string;
  town: string;
  country: string;
}